; =====================================================================
; BalancingWii ULTRA SOFT + HC-05 Bluetooth
; Board  : NUCLEO-F446RE
; PlatformIO config
; =====================================================================

[env:nucleo_f446re]
platform  = ststm32
board     = nucleo_f446re
framework = arduino

; Serial monitor speed
monitor_speed = 115200

; Build flags
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -O2

; Upload via ST-Link (on-board on NUCLEO)
upload_protocol = stlink

; Optional: auto-detect port
; monitor_port = /dev/ttyACM0
